services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: aggregator
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d aggregator" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8001:8001"
    environment:
      DATABASE_URL: postgresql+asyncpg://user:pass@db:5432/aggregator
      REDIS_URL: redis://redis:6379/0
      EVENTS_PROVIDER_BASE_URL: ${EVENTS_PROVIDER_BASE_URL:-https://events-provider.dev-2.python-labs.ru}
      EVENTS_PROVIDER_API_KEY: ${EVENTS_PROVIDER_API_KEY:-your-key-here}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana

  grpc-server:
    build:
      context: .
      dockerfile: Dockerfile.grpc
    container_name: grpc-server
    ports:
      - "8000:8000"

volumes:
  postgres_data:
  redis_data:
  prometheus-data:
  grafana-data:
