"""add_idempotency_table

Revision ID: 9efec3c6b831
Revises: 1b3204d9a869
Create Date: 2026-03-11 17:05:37.935452

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9efec3c6b831"
down_revision: Union[str, Sequence[str], None] = "1b3204d9a869"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "idempotency_keys",
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("ticket_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("seat", sa.String(length=10), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_index(
        "ix_idempotency_created", "idempotency_keys", ["created_at"], unique=False
    )
    op.create_index(
        "ix_idempotency_ticket", "idempotency_keys", ["ticket_id"], unique=False
    )
    op.drop_index(op.f("outbox_pending_fetch"), table_name="outbox")
    op.create_index(
        "ix_outbox_pending_fetch", "outbox", ["status", "created_at"], unique=False
    )
    op.create_index("ix_outbox_retry_count", "outbox", ["retry_count"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_outbox_retry_count", table_name="outbox")
    op.drop_index("ix_outbox_pending_fetch", table_name="outbox")
    op.create_index(op.f("outbox_pending_fetch"), "outbox", ["status"], unique=False)
    op.drop_index("ix_idempotency_ticket", table_name="idempotency_keys")
    op.drop_index("ix_idempotency_created", table_name="idempotency_keys")
    op.drop_table("idempotency_keys")
    # ### end Alembic commands ###
